# Print an optspec for argparse to handle cmd's options that are independent of any subcommand.
function __fish_version_global_optspecs
	string join \n generator= h/help
end

function __fish_version_needs_command
	# Figure out if the current invocation already has a command.
	set -l cmd (commandline -opc)
	set -e cmd[1]
	argparse -s (__fish_version_global_optspecs) -- $cmd 2>/dev/null
	or return
	if set -q argv[1]
		# Also print the command, so this can be used to figure out what it is.
		echo $argv[1]
		return 1
	end
	return 0
end

function __fish_version_using_subcommand
	set -l cmd (__fish_version_needs_command)
	test -z "$cmd"
	and return 1
	contains -- $cmd[1] $argv
end

complete -c version -n "__fish_version_needs_command" -l generator -d 'Generate shell completions' -r -f -a "bash\t''
elvish\t''
fish\t''
powershell\t''
zsh\t''"
complete -c version -n "__fish_version_needs_command" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_needs_command" -f -a "major" -d 'Change the major version number'
complete -c version -n "__fish_version_needs_command" -f -a "minor" -d 'Change the minor version number'
complete -c version -n "__fish_version_needs_command" -f -a "patch" -d 'Change the patch version number'
complete -c version -n "__fish_version_needs_command" -f -a "alpha" -d 'Change the alpha identifier'
complete -c version -n "__fish_version_needs_command" -f -a "beta" -d 'Change the beta identifier'
complete -c version -n "__fish_version_needs_command" -f -a "rc" -d 'Change the release candidate identifier'
complete -c version -n "__fish_version_needs_command" -f -a "build" -d 'Change the build identifier'
complete -c version -n "__fish_version_needs_command" -f -a "get" -d 'Get the current version number as a full SemVer string'
complete -c version -n "__fish_version_needs_command" -f -a "set" -d 'Set the version number to a specific version'
complete -c version -n "__fish_version_needs_command" -f -a "version" -d 'Get just the version number as a string with no revision or build identifiers'
complete -c version -n "__fish_version_needs_command" -f -a "revision" -d 'Get just the revision number as a string with no build identifiers'
complete -c version -n "__fish_version_needs_command" -f -a "file" -d 'Track and update the version number in a file'
complete -c version -n "__fish_version_needs_command" -f -a "package" -d 'Track and update the version number in a file'
complete -c version -n "__fish_version_needs_command" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand major; and not __fish_seen_subcommand_from get set reset help" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand major; and not __fish_seen_subcommand_from get set reset help" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand major; and not __fish_seen_subcommand_from get set reset help" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand major; and not __fish_seen_subcommand_from get set reset help" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand major; and not __fish_seen_subcommand_from get set reset help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand major; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand major; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand major; and __fish_seen_subcommand_from set" -a "+" -d 'Increment the version number by 1'
complete -c version -n "__fish_version_using_subcommand major; and __fish_seen_subcommand_from set" -a "-" -d 'Decrement the version number by 1'
complete -c version -n "__fish_version_using_subcommand major; and __fish_seen_subcommand_from set" -a "up" -d 'Increment the version number by 1'
complete -c version -n "__fish_version_using_subcommand major; and __fish_seen_subcommand_from set" -a "down" -d 'Decrement the version number by 1'
complete -c version -n "__fish_version_using_subcommand major; and __fish_seen_subcommand_from set" -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand major; and __fish_seen_subcommand_from reset" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand major; and __fish_seen_subcommand_from help" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand major; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand major; and __fish_seen_subcommand_from help" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand major; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand minor; and not __fish_seen_subcommand_from get set reset help" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand minor; and not __fish_seen_subcommand_from get set reset help" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand minor; and not __fish_seen_subcommand_from get set reset help" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand minor; and not __fish_seen_subcommand_from get set reset help" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand minor; and not __fish_seen_subcommand_from get set reset help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand minor; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand minor; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand minor; and __fish_seen_subcommand_from set" -a "+" -d 'Increment the version number by 1'
complete -c version -n "__fish_version_using_subcommand minor; and __fish_seen_subcommand_from set" -a "-" -d 'Decrement the version number by 1'
complete -c version -n "__fish_version_using_subcommand minor; and __fish_seen_subcommand_from set" -a "up" -d 'Increment the version number by 1'
complete -c version -n "__fish_version_using_subcommand minor; and __fish_seen_subcommand_from set" -a "down" -d 'Decrement the version number by 1'
complete -c version -n "__fish_version_using_subcommand minor; and __fish_seen_subcommand_from set" -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand minor; and __fish_seen_subcommand_from reset" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand minor; and __fish_seen_subcommand_from help" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand minor; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand minor; and __fish_seen_subcommand_from help" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand minor; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand patch; and not __fish_seen_subcommand_from get set reset help" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand patch; and not __fish_seen_subcommand_from get set reset help" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand patch; and not __fish_seen_subcommand_from get set reset help" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand patch; and not __fish_seen_subcommand_from get set reset help" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand patch; and not __fish_seen_subcommand_from get set reset help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand patch; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand patch; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand patch; and __fish_seen_subcommand_from set" -a "+" -d 'Increment the version number by 1'
complete -c version -n "__fish_version_using_subcommand patch; and __fish_seen_subcommand_from set" -a "-" -d 'Decrement the version number by 1'
complete -c version -n "__fish_version_using_subcommand patch; and __fish_seen_subcommand_from set" -a "up" -d 'Increment the version number by 1'
complete -c version -n "__fish_version_using_subcommand patch; and __fish_seen_subcommand_from set" -a "down" -d 'Decrement the version number by 1'
complete -c version -n "__fish_version_using_subcommand patch; and __fish_seen_subcommand_from set" -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand patch; and __fish_seen_subcommand_from reset" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand patch; and __fish_seen_subcommand_from help" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand patch; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand patch; and __fish_seen_subcommand_from help" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand patch; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand alpha; and not __fish_seen_subcommand_from get set rm reset help" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand alpha; and not __fish_seen_subcommand_from get set rm reset help" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand alpha; and not __fish_seen_subcommand_from get set rm reset help" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand alpha; and not __fish_seen_subcommand_from get set rm reset help" -f -a "rm" -d 'Remove the version identifier'
complete -c version -n "__fish_version_using_subcommand alpha; and not __fish_seen_subcommand_from get set rm reset help" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand alpha; and not __fish_seen_subcommand_from get set rm reset help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from set" -a "+" -d 'Increment the version number by 1'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from set" -a "-" -d 'Decrement the version number by 1'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from set" -a "up" -d 'Increment the version number by 1'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from set" -a "down" -d 'Decrement the version number by 1'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from set" -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from rm" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from reset" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from help" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from help" -f -a "rm" -d 'Remove the version identifier'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from help" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand alpha; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand beta; and not __fish_seen_subcommand_from get set rm reset help" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand beta; and not __fish_seen_subcommand_from get set rm reset help" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand beta; and not __fish_seen_subcommand_from get set rm reset help" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand beta; and not __fish_seen_subcommand_from get set rm reset help" -f -a "rm" -d 'Remove the version identifier'
complete -c version -n "__fish_version_using_subcommand beta; and not __fish_seen_subcommand_from get set rm reset help" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand beta; and not __fish_seen_subcommand_from get set rm reset help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from set" -a "+" -d 'Increment the version number by 1'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from set" -a "-" -d 'Decrement the version number by 1'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from set" -a "up" -d 'Increment the version number by 1'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from set" -a "down" -d 'Decrement the version number by 1'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from set" -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from rm" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from reset" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from help" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from help" -f -a "rm" -d 'Remove the version identifier'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from help" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand beta; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand rc; and not __fish_seen_subcommand_from get set rm reset help" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand rc; and not __fish_seen_subcommand_from get set rm reset help" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand rc; and not __fish_seen_subcommand_from get set rm reset help" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand rc; and not __fish_seen_subcommand_from get set rm reset help" -f -a "rm" -d 'Remove the version identifier'
complete -c version -n "__fish_version_using_subcommand rc; and not __fish_seen_subcommand_from get set rm reset help" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand rc; and not __fish_seen_subcommand_from get set rm reset help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from set" -a "+" -d 'Increment the version number by 1'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from set" -a "-" -d 'Decrement the version number by 1'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from set" -a "up" -d 'Increment the version number by 1'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from set" -a "down" -d 'Decrement the version number by 1'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from set" -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from rm" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from reset" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from help" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from help" -f -a "rm" -d 'Remove the version identifier'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from help" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand rc; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand build; and not __fish_seen_subcommand_from get set rm help" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand build; and not __fish_seen_subcommand_from get set rm help" -f -a "get"
complete -c version -n "__fish_version_using_subcommand build; and not __fish_seen_subcommand_from get set rm help" -f -a "set" -d 'Set the build version'
complete -c version -n "__fish_version_using_subcommand build; and not __fish_seen_subcommand_from get set rm help" -f -a "rm"
complete -c version -n "__fish_version_using_subcommand build; and not __fish_seen_subcommand_from get set rm help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand build; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand build; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand build; and __fish_seen_subcommand_from rm" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand build; and __fish_seen_subcommand_from help" -f -a "get"
complete -c version -n "__fish_version_using_subcommand build; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set the build version'
complete -c version -n "__fish_version_using_subcommand build; and __fish_seen_subcommand_from help" -f -a "rm"
complete -c version -n "__fish_version_using_subcommand build; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand get" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand set" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand version" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand revision" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand file; and not __fish_seen_subcommand_from track rm update update-all list help" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand file; and not __fish_seen_subcommand_from track rm update update-all list help" -f -a "track" -d 'Add a file to add the version number'
complete -c version -n "__fish_version_using_subcommand file; and not __fish_seen_subcommand_from track rm update update-all list help" -f -a "rm" -d 'Remove a file from tracking the version number'
complete -c version -n "__fish_version_using_subcommand file; and not __fish_seen_subcommand_from track rm update update-all list help" -f -a "update" -d 'Set the version number from a file'
complete -c version -n "__fish_version_using_subcommand file; and not __fish_seen_subcommand_from track rm update update-all list help" -f -a "update-all" -d 'Update all files'
complete -c version -n "__fish_version_using_subcommand file; and not __fish_seen_subcommand_from track rm update update-all list help" -f -a "list" -d 'List tracked files'
complete -c version -n "__fish_version_using_subcommand file; and not __fish_seen_subcommand_from track rm update update-all list help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand file; and __fish_seen_subcommand_from track" -s h -l help -d 'Print help (see more with \'--help\')'
complete -c version -n "__fish_version_using_subcommand file; and __fish_seen_subcommand_from rm" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand file; and __fish_seen_subcommand_from update" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand file; and __fish_seen_subcommand_from update-all" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand file; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand file; and __fish_seen_subcommand_from help" -f -a "track" -d 'Add a file to add the version number'
complete -c version -n "__fish_version_using_subcommand file; and __fish_seen_subcommand_from help" -f -a "rm" -d 'Remove a file from tracking the version number'
complete -c version -n "__fish_version_using_subcommand file; and __fish_seen_subcommand_from help" -f -a "update" -d 'Set the version number from a file'
complete -c version -n "__fish_version_using_subcommand file; and __fish_seen_subcommand_from help" -f -a "update-all" -d 'Update all files'
complete -c version -n "__fish_version_using_subcommand file; and __fish_seen_subcommand_from help" -f -a "list" -d 'List tracked files'
complete -c version -n "__fish_version_using_subcommand file; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "major" -d 'Change the major version number'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "minor" -d 'Change the minor version number'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "patch" -d 'Change the patch version number'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "alpha" -d 'Change the alpha identifier'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "beta" -d 'Change the beta identifier'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "rc" -d 'Change the release candidate identifier'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "build" -d 'Change the build identifier'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "get" -d 'Get the current version number as a full SemVer string'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "set" -d 'Set the version number to a specific version'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "version" -d 'Get just the version number as a string with no revision or build identifiers'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "revision" -d 'Get just the revision number as a string with no build identifiers'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "file" -d 'Track and update the version number in a file'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "rm" -d 'Remove a package'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "list" -d 'List tracked packages'
complete -c version -n "__fish_version_using_subcommand package; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file rm list help" -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from major" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from major" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from major" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from major" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from major" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from minor" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from minor" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from minor" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from minor" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from minor" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from patch" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from patch" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from patch" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from patch" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from patch" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from alpha" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from alpha" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from alpha" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from alpha" -f -a "rm" -d 'Remove the version identifier'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from alpha" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from alpha" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from beta" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from beta" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from beta" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from beta" -f -a "rm" -d 'Remove the version identifier'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from beta" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from beta" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from rc" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from rc" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from rc" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from rc" -f -a "rm" -d 'Remove the version identifier'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from rc" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from rc" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from build" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from build" -f -a "get"
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from build" -f -a "set" -d 'Set the build version'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from build" -f -a "rm"
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from build" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from get" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from set" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from version" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from revision" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from file" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from file" -f -a "track" -d 'Add a file to add the version number'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from file" -f -a "rm" -d 'Remove a file from tracking the version number'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from file" -f -a "update" -d 'Set the version number from a file'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from file" -f -a "update-all" -d 'Update all files'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from file" -f -a "list" -d 'List tracked files'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from file" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from rm" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from list" -s h -l help -d 'Print help'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "major" -d 'Change the major version number'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "minor" -d 'Change the minor version number'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "patch" -d 'Change the patch version number'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "alpha" -d 'Change the alpha identifier'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "beta" -d 'Change the beta identifier'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "rc" -d 'Change the release candidate identifier'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "build" -d 'Change the build identifier'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "get" -d 'Get the current version number as a full SemVer string'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "set" -d 'Set the version number to a specific version'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "version" -d 'Get just the version number as a string with no revision or build identifiers'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "revision" -d 'Get just the revision number as a string with no build identifiers'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "file" -d 'Track and update the version number in a file'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "rm" -d 'Remove a package'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "list" -d 'List tracked packages'
complete -c version -n "__fish_version_using_subcommand package; and __fish_seen_subcommand_from help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "major" -d 'Change the major version number'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "minor" -d 'Change the minor version number'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "patch" -d 'Change the patch version number'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "alpha" -d 'Change the alpha identifier'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "beta" -d 'Change the beta identifier'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "rc" -d 'Change the release candidate identifier'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "build" -d 'Change the build identifier'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "get" -d 'Get the current version number as a full SemVer string'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "set" -d 'Set the version number to a specific version'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "version" -d 'Get just the version number as a string with no revision or build identifiers'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "revision" -d 'Get just the revision number as a string with no build identifiers'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "file" -d 'Track and update the version number in a file'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "package" -d 'Track and update the version number in a file'
complete -c version -n "__fish_version_using_subcommand help; and not __fish_seen_subcommand_from major minor patch alpha beta rc build get set version revision file package help" -f -a "help" -d 'Print this message or the help of the given subcommand(s)'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from major" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from major" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from major" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from minor" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from minor" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from minor" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from patch" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from patch" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from patch" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from alpha" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from alpha" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from alpha" -f -a "rm" -d 'Remove the version identifier'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from alpha" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from beta" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from beta" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from beta" -f -a "rm" -d 'Remove the version identifier'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from beta" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from rc" -f -a "get" -d 'Print the current version'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from rc" -f -a "set" -d 'Set the version number'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from rc" -f -a "rm" -d 'Remove the version identifier'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from rc" -f -a "reset" -d 'Reset the subversions'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from build" -f -a "get"
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from build" -f -a "set" -d 'Set the build version'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from build" -f -a "rm"
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from file" -f -a "track" -d 'Add a file to add the version number'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from file" -f -a "rm" -d 'Remove a file from tracking the version number'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from file" -f -a "update" -d 'Set the version number from a file'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from file" -f -a "update-all" -d 'Update all files'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from file" -f -a "list" -d 'List tracked files'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "major" -d 'Change the major version number'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "minor" -d 'Change the minor version number'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "patch" -d 'Change the patch version number'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "alpha" -d 'Change the alpha identifier'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "beta" -d 'Change the beta identifier'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "rc" -d 'Change the release candidate identifier'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "build" -d 'Change the build identifier'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "get" -d 'Get the current version number as a full SemVer string'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "set" -d 'Set the version number to a specific version'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "version" -d 'Get just the version number as a string with no revision or build identifiers'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "revision" -d 'Get just the revision number as a string with no build identifiers'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "file" -d 'Track and update the version number in a file'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "rm" -d 'Remove a package'
complete -c version -n "__fish_version_using_subcommand help; and __fish_seen_subcommand_from package" -f -a "list" -d 'List tracked packages'
